name: Minimal CMake Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
      fail-fast: true
    defaults:
      run:
        working-directory: ch11/part-4/app
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'
      - name: Install OpenGL
        run: sudo apt-get install libgles2-mesa-dev
      - name: Compiler version
        run: gcc --version
      - name: Configure and build (Debug)
        run: |
          cmake --preset multi-ninja-super-test
          cmake --build build/multi-ninja-super-test
      - name: Run tests
        id: run_tests
        continue-on-error: true
        run: |
          ./build/multi-ninja-super-test/Debug/minimal-cmake_game-of-life_window-test 2>&1 | tee errors.txt
      - name: Show errors  
        if: steps.run_tests.outcome == 'failure'
        run: |
          cat errors.txt
        # run: |
          # ctest --preset multi-ninja-super-test > test.log
          # cat test.log
      - uses: actions/upload-artifact@v2
        if: steps.run_tests.outcome == 'failure'
        with:
          name: test-output
          path: errors.txt
      - name: Build and package (Release)
        run: >
          cmake --workflow --preset multi-ninja-super-package-linux
