name: Minimal CMake Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
      fail-fast: true
    defaults:
      run:
        working-directory: ch11/part-4/app
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'
      - name: C compiler
        run: gcc --version
      - name: C++ compiler
        run: g++ --version
      - name: Configure and build
        run: >
          cmake --workflow --preset multi-ninja-super-test
      - name: Run tests          
        run: >
          ctest --preset multi-ninja-super-test
      - name: Build and package
        run: >
          cmake --workflow --preset multi-ninja-super-package-linux
