name: Minimal CMake Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-13
      CXX: g++-13
    strategy:
      matrix:
        cmake-version: [3.28]
      fail-fast: true
    defaults:
      run:
        working-directory: ch11/part-4/app
    steps:
      - uses: actions/checkout@v4
        with:
          cmake-version: ${{ matrix.cmake-version }}
      - name: Configure and build
        run: >
          cmake --workflow --preset multi-ninja-super-test
      - name: Run tests          
        run: >
          ctest --preset multi-ninja-super-test
      - name: Build and package
        run: >
          cmake --workflow --preset multi-ninja-super-package-linux
